server:
  port: 14000
spring:
  datasource:
    url: jdbc:mysql://192.168.200.100:3306/gmall_order?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: sharding
app:
  threadpool:
    core-pool-size: 4
    maximum-pool-size: 8
    keep-alive-time: 60
    work-queue-size: 200