server:
  port: 80
spring:
  cloud:
    sentinel:
      enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"  #允许所有来源访问
            allowedMethods: "*"  #允许所有请求方式跨域访问
            allowedHeaders: "*"  #运行任意请求头跨域
            allowCredentials: true #运行cookie等一些安全头跨域

      routes:
        - id: user_route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**

        - id: incr_test
          uri: lb://service-product
          predicates:
            - Path=/incr

        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

        - id: activity_route
          uri: lb://service-activity
          predicates:
            - Path=/admin/activity/**

        - id: front_route
          uri: lb://web-front
          predicates:
              - Host=**.gmall.com
app:
  auth:
    login-url:
      - /order/**
    no-auth-url:
      - /rpc/inner/**
    login-page: http://passport.gmall.com/login.html
