server:
  port: 8000
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true

##配置feignClient
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 1000
#        readTimeout: 5000
#        retryer: com.atguigu.gmall.common.retry.RequestNeverRetryer