server:
  port: 8000
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true